# Generated by Django 2.1.4 on 2019-09-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=32, unique=True, verbose_name='部门名称')),
                ('dep_script', models.CharField(max_length=60, null=True, verbose_name='备注')),
            ],
        ),
    ]
