# Generated by Django 2.1.4 on 2019-09-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loguser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32, verbose_name='登录账号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
        ),
    ]
