# Generated by Django 2.1.4 on 2019-09-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_view', '0002_loguser'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('gander', models.CharField(choices=[(1, '男'), (2, '女')], max_length=1)),
                ('head_img', models.ImageField(blank=True, null=True, upload_to='headimage')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='filedir')),
            ],
        ),
    ]
