# Generated by Django 2.1.4 on 2019-09-20 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtest',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogtest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogtest',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Blogtest',
        ),
    ]
