# Generated by Django 2.1.4 on 2019-09-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者基本情况', 'verbose_name_plural': '作者基本情况'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书信息', 'verbose_name_plural': '图书信息'},
        ),
        migrations.AlterModelOptions(
            name='publishing',
            options={'verbose_name': '出版社信息', 'verbose_name_plural': '出版社书信息'},
        ),
        migrations.AlterField(
            model_name='publishing',
            name='address',
            field=models.CharField(max_length=20, verbose_name='出版社地址'),
        ),
    ]
