# Generated by Django 2.1.4 on 2019-08-26 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loguser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32, verbose_name='登录账号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('gander', models.CharField(max_length=1)),
                ('hobby', models.CharField(max_length=20)),
                ('hair', models.CharField(max_length=1)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
        ),
    ]
