# Generated by Django 2.1.4 on 2019-08-27 03:24

from django.db import migrations, models
import utils.rename_upload


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190827_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loguser',
            name='img',
            field=models.ImageField(blank=True, null=True, storage=utils.rename_upload.RenameUpload(), upload_to='image'),
        ),
    ]
