# Generated by Django 2.1.4 on 2019-08-27 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20190827_1124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loguser',
        ),
    ]
