# Generated by Django 2.1.4 on 2019-08-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_form', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loguser',
        ),
    ]
