# Generated by Django 2.1.4 on 2019-10-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=32, verbose_name='权限代码')),
                ('url', models.CharField(max_length=128, verbose_name='URL表达式')),
                ('name', models.CharField(max_length=120, verbose_name='权限描述')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
            },
        ),
    ]
