# Generated by Django 2.0 on 2019-09-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=7, unique=True, verbose_name='车牌号')),
                ('driver', models.CharField(max_length=10, verbose_name='司机')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('remarks', models.CharField(max_length=32, verbose_name='备注说明')),
            ],
        ),
    ]
