# Generated by Django 2.1.4 on 2019-10-19 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('fare', '0003_auto_20191019_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='loguser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_img', models.ImageField(blank=True, null=True, upload_to='headimage', verbose_name='头像')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fare.department')),
                ('user_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='fare',
            name='oprator',
        ),
    ]
