# Generated by Django 2.1.4 on 2019-10-19 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fare', '0005_auto_20191019_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loguser',
            name='dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fare.department'),
        ),
        migrations.AlterField(
            model_name='loguser',
            name='user_obj',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo'),
        ),
    ]
