# Generated by Django 2.1.4 on 2019-10-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fare', '0006_auto_20191019_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fare',
            name='car',
        ),
        migrations.RemoveField(
            model_name='fare',
            name='dep',
        ),
        migrations.DeleteModel(
            name='fare',
        ),
    ]
