# Generated by Django 2.1.4 on 2019-10-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fare', '0007_auto_20191019_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='fare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.CharField(max_length=32, verbose_name='乘车人')),
                ('driver', models.CharField(max_length=10, verbose_name='司机')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('distance', models.IntegerField(verbose_name='公里数')),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='车费')),
                ('drive_date', models.DateField(auto_now_add=True, null=True, verbose_name='乘车时间')),
                ('remark', models.CharField(max_length=100, verbose_name='乘车说明')),
                ('oprator', models.CharField(max_length=32, verbose_name='录入人员')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fare.carinfo')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fare.department')),
            ],
        ),
    ]
