# Generated by Django 2.1.4 on 2019-10-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fare', '0008_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='fare',
            name='approve_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='fare',
            name='approve_status',
            field=models.CharField(blank=True, choices=[('0', '未审批'), ('1', '通过审批')], max_length=1, null=True, verbose_name='审批状态'),
        ),
    ]
